name: Upload Python Package

on:
  push:
  release:
    types: [published]

permissions:
  contents: write  # Needed for uploading files to the release
  id-token: write  # Needed for OIDC PyPI publishing

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.baipp.outputs.package_version }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: hynek/build-and-inspect-python-package@efb823f52190ad02594531168b7a2d5790e66516 # v2.14.0
      id: baipp

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    environment:
      name: publishing
      url: https://pypi.org/project/meltanolabs-tap-postgres/${{ needs.build.outputs.version }}

    steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: Packages
        path: dist
    - uses: svenstaro/upload-release-action@b98a3b12e86552593f3e4e577ca8a62aa2f3f22b # 2.11.4
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.whl
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    - name: Deploy to PyPI
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
